--- 
title: "Income, Education, Smoking and Cancer"
author: "Michael Zhou"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

We all know by common sense that smoking is one of the leading causes to many kinds of cancer (lung, breast, colon, etc.). Studies have also shown that socioeconomic indicators, such as income and education, are related to smoking rates, which corresponds with a higher cancer rate, as middle-income countries are claimed to have more smokers (due to the lack of education and affordability of tobacco) as shown [here](https://www.youtube.com/watch?v=QBht72_PA-4), and more educated are claimed to be less likely to smoke as described in [this article](https://truthinitiative.org/research-resources/targeted-communities/economics-tobacco-what-education-and-income-tell-us-about) and [this article](https://journals.lww.com/oncology-times/fulltext/2014/06250/cdc_data__cigarette_smoking_by_education_level_and.26.aspx). In this project, we are interested in corroborating these three claims by learning about the statistical relationships between average income, education level, smoking rates, and cancer rates. 

We work with four datasets (each representing different indicators): [Educational Attainment by US State](https://worldpopulationreview.com/state-rankings/educational-attainment-by-state),  [Average Income by US State](https://worldpopulationreview.com/state-rankings/average-income-by-state ), [Average Smoking Rates by US State](https://worldpopulationreview.com/state-rankings/smoking-rates-by-state ), and [Cancer Rates by US State](https://worldpopulationreview.com/state-rankings/cancer-rates-by-state ). All four datasets are collected from [World Population Review](https://worldpopulationreview.com/), and each dataset is collected from a separate website. We will be inspecting each indicators as well as the relationships between each variable per US state. 

We plan to inspect each indicator separately by geography using heat maps. To explore the statistical relationships, we use EDA techniques such as scatter plot matrices and correlation plots between the different indicators. 