# Interactive Component

Below are the top or bottom 5 US states for each indicator:

```{r fig.height = 10, fig.width = 10}
# library(ggplot2)
# library(corrplot)
# library(ggiraph)
# library(tidyverse)
# 
# pd <- df %>%
#   select(-c("abb", "state")) %>%
#   cor() 
# 
# pd[upper.tri(pd)] <- NA
# pd <- reshape2::melt(pd, na.rm = TRUE)
# colors = c("blue", "white", "red")
# # Create ggplot2
# p1 <- ggplot(pd) +
#   geom_tile(aes(Var1, Var2, fill = value), color = "gray")  +
#   scale_fill_gradient2(low = colors[1], high = colors[3],
#                        mid = colors[2], midpoint = 0, limit = c(-1, 1), space = "Lab",
#                        name = "Corr") +
#   geom_text(mapping = aes(x = Var1, y = Var2, label = round(value, 1)), size = 2) +
#   ggplot2::coord_fixed() +
#   theme_minimal() +
#   theme(axis.text.x = element_text(angle = 45,
#                                    vjust = 1, size = 8, hjust = 1),
#         axis.text.y = element_text(size = 8),
#         legend.position = 'bottom') +
#   guides(fill = FALSE) +
# #  guides(fill = guide_colorbar(title = NULL, barwidth = unit(0.6, "npc"))) +
#   xlab("") + ylab("") 
# 
# pd2 <- pd %>% 
#   mutate(data_id = paste0(Var1, '-', Var2),
#          tooltip = paste0(Var1, '-', Var2, ': ', round(value, 2)))
# p2 <- ggplot(pd2) +
#   geom_tile_interactive(aes(Var1, Var2, fill = value,
#                             tooltip = tooltip
#                             ), color = "gray")  +
#   scale_fill_gradient2(low = colors[1], high = colors[3],
#                        mid = colors[2], midpoint = 0, limit = c(-1, 1), space = "Lab",
#                        name = "Corr") +
#   geom_text(mapping = aes(x = Var1, y = Var2, label = round(value, 2)), size = 2) +
#   ggplot2::coord_fixed() +
#   theme_minimal() +
#   theme(axis.text.x = element_text(angle = 45,
#                                    vjust = 1, size = 8, hjust = 1),
#         axis.text.y = element_text(size = 8),
#         legend.position = 'bottom') +
#   guides(fill = FALSE) +
# #  guides(fill = guide_colorbar(title = NULL, barwidth = unit(0.6, "npc"))) +
#   xlab("") + ylab("")
# # girafe(ggobj = p2)
# 
# knitr::raw_html('
# <script type="text/javascript">
#   
# var create_fig = function(valuex, valuey, xlabel, ylabel) {
#   var margin = {top: 10, right: 30, bottom: 50, left: 70},
#   width = 460 - margin.left - margin.right,
#   height = 400 - margin.top - margin.bottom;
#   
#   // Remove old plot
#   var svg1 = d3.select("#comparison-plot");
#   svg1.selectAll("*").remove();
#   // append the svg object to the body of the page
#   
#   var svg = d3.select("#comparison-plot")
#     .append("svg")
#       .attr("width", width + margin.left + margin.right)
#       .attr("height", height + margin.top + margin.bottom)
#     .append("g")
#       .attr("transform",
#             "translate(" + margin.left + "," + margin.top + ")");
#   // Add X axis
#   var x = d3.scaleLinear()
#     .domain([Math.min(...valuex), Math.max(...valuex)])
#     .range([ 0, width ]);
#   svg.append("g")
#     .attr("transform", "translate(0," + height + ")")
#     .call(d3.axisBottom(x));
#   svg.append("text")
#     .attr("class", "x label")
#     .attr("text-anchor", "end")
#     .attr("x", margin.left + width / 2)
#     .attr("y", margin.top + height + 30)
#     .text(xlabel);
#   // Add Y axis
#   var y = d3.scaleLinear()
#     .domain([Math.min(...valuey), Math.max(...valuey)])
#     .range([ height, 0]);
#   svg.append("text")
#     .attr("class", "y label")
#     .attr("text-anchor", "end")
#     .attr("y", -50)
#     .attr("x", -(height / 2) + margin.top)
#     .attr("transform", "rotate(-90)")
#     .text(ylabel);
#   svg.append("g")
#     .call(d3.axisLeft(y));
#   // Create data item
#   var data = valuex.map((item, i) => ({x:item, y:valuey[i]}))
#   // Add dots
#   svg.append("g")
#     .selectAll("dot")
#     .data(data)
#     .enter()
#     .append("circle")
#       .attr("cx", function (d) { return x(d.x); } )
#       .attr("cy", function (d) { return y(d.y); } )
#       .attr("r", 4)
#       .style("fill", "#69b3a2")
#   }
# </script>
# ')
# 
# # Generate js to create_fig
# generate_js <- function(data) {
#   x <- df[[data$Var1]]
#   y <- df[[data$Var2]]
#   data$onclick <- paste0("create_fig(", 
#          jsonlite::toJSON(x), ", ",
#          jsonlite::toJSON(y), ", ",
#          '"', data$Var1, '", ',
#          '"', data$Var2, '"',
#          ")")
#   data
# }
# 
# # Create a new data frame
# pd3 <- pd2 %>% 
#   group_by(Var1, Var2) %>% 
#   do(generate_js(.))
# 
# p3 <- ggplot(pd3) +
#   geom_tile_interactive(aes(Var1, Var2, fill = value,
#                             tooltip = tooltip,
#                             data_id = data_id,
#                             onclick = onclick
#                             ), color = "gray")  +
#   scale_fill_gradient2(low = colors[1], high = colors[3],
#                        mid = colors[2], midpoint = 0, limit = c(-1, 1), space = "Lab",
#                        name = "Corr") +
#   geom_text(mapping = aes(x = Var1, y = Var2, label = round(value, 2)), size = 2) +
#   ggplot2::coord_fixed() +
#   theme_minimal() +
#   theme(axis.text.x = element_text(angle = 45,
#                                    vjust = 1, size = 8, hjust = 1),
#         axis.text.y = element_text(size = 8),
#         legend.position = 'bottom') +
#   guides(fill = FALSE) +
# #  guides(fill = guide_colorbar(title = NULL, barwidth = unit(0.6, "npc"))) +
#   xlab("") + ylab("")
# girafe(ggobj = p3)

# # Write to CSV
# write.csv(pd, 'corr.csv')
```


<meta charset="utf-8">
<title>NYUJobs></title>
<style type="text/css">
			h1 {color:black;}		/* CSS styling */
			p {color:blue;}
</style>
<body>
<!-- Load d3.js -->
<script src="https://d3js.org/d3.v4.js"></script>
<h1>Top/Bottom 5 States for each Indicator</h1>
 </h3>
<!-- Add buttons -->

<div class="population_density">
  <button onclick="update(population_density_top_5)">Top 5 Densely Populated States</button>
  <button onclick="update(population_density_bottom_5)">Bottom 5 Densely Populated States</button>
</div>

<div class="avg_income">
  <button onclick="update(avg_income_top_5)">Top 5 States in Average Income</button>
  <button onclick="update(avg_income_bottom_5)">Bottom 5 States in Average Income</button>
</div>

<div class="median_income">
  <button onclick="update(median_income_top_5)">Top 5 States in Median Income</button>
  <button onclick="update(median_income_bottom_5)">Bottom 5 States in Median Income</button>
</div>


<div class="education_highschool">
  <button onclick="update(education_highschool_top_5)">Top 5 States in HS Graduation</button>
  <button onclick="update(education_highschool_bottom_5)">Bottom 5 States in HS Graduation</button>
</div>

<div class="education_college">
  <button onclick="update(education_college_top_5)">Top 5 States in College Graduation</button>
  <button onclick="update(education_college_bottom_5)">Bottom 5 States in College Graduation</button>
</div>
  
<div class="smoking_rates">
  <button onclick="update(smoking_rates_top_5)">Top 5 States in Smoking Rates</button>
  <button onclick="update(smoking_rates_bottom_5)">Bottom 5 States in Smoking Rates</button>
</div>

<div class="cancer_rates">
  <button onclick="update(cancer_rates_top_5)">Top 5 States in Cancer Rates</button>
  <button onclick="update(cancer_rates_bottom_5)">Bottom 5 States in Cancer Rates</button>
</div>


<!-- Create a div where the graph will take place -->
<div id="d3try" ></div>
<script>
// create  data_set
var population_density_top_5 = [   
   {state: "NJ", value: 1283.4000	},
   {state: "RI", value: 1074.2959},
   {state: "MA", value: 919.8210},
   {state: "CT", value: 746.6954},
   {state: "MD", value: 648.8436}
];

var population_density_bottom_5 = [
  {
    "state": "AK",
    "value": 1.2974
  },
  {
    "state": "WY",
    "value": 5.9821
  },
  {
    "state": "MT",
    "value": 7.6448
  },
  {
    "state": "ND",
    "value": 11.7541
  },
  {
    "state": "SD",
    "value": 11.9826
  }
];

var avg_income_top_5 = [
  {
    "state": "NJ",
    "value": 117868
  },
  {
    "state": "MA",
    "value": 115964
  },
  {
    "state": "CT",
    "value": 115337
  },
  {
    "state": "MD",
    "value": 114236
  },
  {
    "state": "CA",
    "value": 111622
  }];

var avg_income_bottom_5 = [
  {
    "state": "MS",
    "value": 65156
  },
  {
    "state": "WV",
    "value": 65332
  },
  {
    "state": "AR",
    "value": 69357
  },
  {
    "state": "NM",
    "value": 70241
  },
  {
    "state": "AL",
    "value": 71964
  }
];

var median_income_top_5 = [
  {
    "state": "MD",
    "value": 87063
  },
  {
    "state": "NJ",
    "value": 85245
  },
  {
    "state": "MA",
    "value": 84385
  },
  {
    "state": "HI",
    "value": 83173
  },
  {
    "state": "CT",
    "value": 79855
  }
];

var median_income_bottom_5 = [
  {
    "state": "MS",
    "value": 46511
  },
  {
    "state": "WV",
    "value": 48037
  },
  {
    "state": "AR",
    "value": 49475
  },
  {
    "state": "LA",
    "value": 50800
  },
  {
    "state": "NM",
    "value": 51243
  }
];


var education_highschool_top_5 = [
  {
    "state": "MT",
    "value": 94
  },
  {
    "state": "WY",
    "value": 93.6
  },
  {
    "state": "VT",
    "value": 93.5
  },
  {
    "state": "MN",
    "value": 93.4
  },
  {
    "state": "NH",
    "value": 93.3
  }
]; 

var education_highschool_bottom_5 = [
  {
    "state": "CA",
    "value": 83.9
  },
  {
    "state": "TX",
    "value": 84.4
  },
  {
    "state": "MS",
    "value": 85.3
  },
  {
    "state": "LA",
    "value": 85.9
  },
  {
    "state": "NM",
    "value": 86.5
  }
]; 

var education_college_top_5 = [
  {
    "state": "MA",
    "value": 44.5
  },
  {
    "state": "CO",
    "value": 41.6
  },
  {
    "state": "MD",
    "value": 40.9
  },
  {
    "state": "NJ",
    "value": 40.7
  },
  {
    "state": "CT",
    "value": 40
  }
]; 

var education_college_bottom_5 = [
  {
    "state": "WV",
    "value": 21.3
  },
  {
    "state": "MS",
    "value": 22.8
  },
  {
    "state": "AR",
    "value": 23.8
  },
  {
    "state": "LA",
    "value": 24.9
  },
  {
    "state": "KY",
    "value": 25
  }
];

var smoking_rates_top_5 = [
  {
    "state": "WV",
    "value": 23.8
  },
  {
    "state": "KY",
    "value": 23.6
  },
  {
    "state": "LA",
    "value": 21.9
  },
  {
    "state": "OH",
    "value": 20.8
  },
  {
    "state": "MS",
    "value": 20.4
  }
];

var smoking_rates_bottom_5 = [
  {
    "state": "UT",
    "value": 7.9
  },
  {
    "state": "CA",
    "value": 10
  },
  {
    "state": "MA",
    "value": 12
  },
  {
    "state": "CT",
    "value": 12.1
  },
  {
    "state": "HI",
    "value": 12.3
  }
];

var cancer_rates_top_5 = [
  {
    "state": "KY",
    "value": 510.2
  },
  {
    "state": "NJ",
    "value": 482.4
  },
  {
    "state": "WV",
    "value": 482.4
  },
  {
    "state": "NY",
    "value": 480.6
  },
  {
    "state": "LA",
    "value": 478.6
  }
];

var cancer_rates_bottom_5 = [
  {
    "state": "SD",
    "value": 49.6
  },
  {
    "state": "IA",
    "value": 77.3
  },
  {
    "state": "NM",
    "value": 361.1
  },
  {
    "state": "AZ",
    "value": 374.9
  },
  {
    "state": "CA",
    "value": 392.4
  }
];

// set the dimensions and margins of the graph
var margin = {top: 30, right: 30, bottom: 70, left: 60},
    width = 800 - margin.left - margin.right,
    height = 450 - margin.top - margin.bottom;

// append the svg object to the body of the page
var svg = d3.select("#d3try")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")")
   .append("g", id ='circ');
  
// Initialize the X axis
var x = d3.scaleBand()
  .range([ 0, width ])
  .padding(0.2);
var xAxis = svg.append("g")
  .attr("transform", "translate(0," + height + ")")

// Initialize the Y axis
var y = d3.scaleLinear()
  .range([ height, 0]);
var yAxis = svg.append("g")
  .attr("class", "myYaxis")

// A function that create / update the plot for a given variable:
function update(data) {

  // Update the X axis
  x.domain(data.map(function(d) { return d.state; }))
  xAxis.call(d3.axisBottom(x))

  // Update the Y axis
  y.domain([0, d3.max(data, function(d) { return d.value }) ]);
  yAxis.transition().duration(1000).call(d3.axisLeft(y));

  // Create the u variable
  var u = svg.selectAll("rect")
    .data(data)

  u
    .enter()
    .append("rect") // Add a new rect for each new elements
    .merge(u) // get the already existing elements as well
    .transition() // and apply changes to all of them
    .duration(1000)
      .attr("x", function(d) { return x(d.state); })
      .attr("y", function(d) { return y(d.value); })
      .attr("width", x.bandwidth())
      .attr("height", function(d) { return height - y(d.value); })
      .attr("fill", "#7b6888")

var rect = svg.selectAll("rect").on("mouseover", function(d, i) {
               //highlight
                 d3.select(this).style("fill","#BA5C25");
                })
            .on("mouseout", function(d) {
                 d3.select(this).style("fill","#7b6888");
                });

  // If less group in the new dataset, I delete the ones not in use anymore
  u
    .exit()
    .remove()
    
      
    
}
update(data1)

</script>
</body>

